import type { Metadata } from 'next';
import { Merriweather, Orbitron } from 'next/font/google';

// import Scroller from '@components/Scroller';

import './globals.css';

const orbitron = Orbitron({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-orbitron',
  display: 'swap',
});

const merriweather = Merriweather({
  subsets: ['latin'],
  weight: ['300', '400'],
  variable: '--font-merriweather',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`${merriweather.variable} ${orbitron.variable} w-full bg-gradient-to-b from-[#16161d] via-[#1f1f3a] to-[#3b2f4a]`}
    >
      <body className='flex flex-col font-primary'>
        {/* <Scroller> */}

        {children}
        {/* </Scroller> */}
      </body>
    </html>
  );
}
