import type { Metadata } from 'next';
import { Merriweather } from 'next/font/google';
import '../globals.css';

import Header from '../../components/Header';

const merriweather = Merriweather({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={merriweather.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
