import type { Metadata } from 'next';
import { Merriweather, Orbitron } from 'next/font/google';
import '../globals.css';

import Header from '../../components/Header';

const orbitron = Orbitron({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-orbitron',
  display: 'swap',
});

const merriweather = Merriweather({
  subsets: ['latin'],
  weight: ['300', '400'],
  variable: '--font-merriweather',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`${merriweather.variable} ${orbitron.variable} w-full`}
    >
      <body className='font-primary flex flex-col'>
        <Header />

        {children}
      </body>
    </html>
  );
}
